### ISSUE TITLE
Still working on this?

### ISSUE THREAD

**Issue by Gregoor** [wangyanxing/graphql_idea_plugin#1]
Just read your working on this in facebook/graphql#79. Any progress?

If not, I might take a swing at it.

**Comment by wangyanxing** [comment]
Hi there,

I am busy recently  and you can take over this for sure!

Thanks,
Yanxing

**Comment by Gregoor** [comment]
Okay, thanks for getting back to me :)

Current basic version can be found here, if you're interested:
https://github.com/Gregoor/graphql-intellij-plugin
